name: Test/Deploy Master

on:
  push:
    branches: ['[0-9]+.[0-9]+']

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - name: Eslint check
        run: yarn run lint
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          build: yarn run build
          start: yarn run dev
          wait-on: "http://localhost:5173"
          browser: chrome
  deploy-docs:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Developer Event
        uses: peter-evans/repository-dispatch@main
        with:
          token: ${{ secrets.DOCS_REFRESH_TOKEN }}
          repository: neo4j-documentation/docs-refresh
          event-type: labs